// 라방바 데이터랩(live.ecomm-data.com/assignment) TOP10 방송 리스트 데이터.
// 필드 설명
// - rank: 순위 (1~10)
// - title: 방송 제목
// - channel: 채널명 (예: 네이버쇼핑LIVE, CJ온스타일 등)
// - category: 분류 (예: 디지털/가전, 패션의류 등)
// - broadcastTime: ISO 형식 문자열
// - metricLabel: 라방이면 "조회수", 홈쇼핑이면 "시청률"
// - metricValue: 로그인 후에만 보이는 값. 값이 없으면(null) 화면에 🔒 표시
// - sales: 판매량
// - revenue: 매출액 (원본 페이지 표기 그대로 문자열로 저장, 예: "352만", "2.12억")
// - productCount: 상품수
//
// 2026-07-17 (금) 기준, 로그인 상태에서 직접 확인한 스냅샷.
// 실시간 랭킹 데이터라 조회 시점마다 값이 달라짐 -> 특정 시점 스냅샷임을 README에 명시.
export const liveBroadcasts = [
  {
    rank: 1,
    title: '다시보는 맘만하니💙삼익가구 베이비장, 리클라이너 등🛋️',
    channel: 'CJ온스타일',
    category: '가구/인테리어',
    broadcastTime: '2026-07-17T16:00:00',
    metricLabel: '조회수',
    metricValue: 1174,
    sales: 8,
    revenue: '352만',
    productCount: 60,
  },
  {
    rank: 2,
    title: '[Ai Live] LG그램 프로 & 그램북 노트북 14/15/16/17형',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T15:01:00',
    metricLabel: '조회수',
    metricValue: 232,
    sales: 1,
    revenue: '345만',
    productCount: 28,
  },
  {
    rank: 3,
    title: '[AI라이브]LIVE 중에만 이 가격! 삼성 세탁기 라이브 혜택 찬스',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T15:00:00',
    metricLabel: '조회수',
    metricValue: 353,
    sales: 1,
    revenue: '330만',
    productCount: 30,
  },
  {
    rank: 4,
    title: '[삼성공식인증점💙] 장마철 필수템☔ 세탁기 건조기 AI 라이브 특가',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T14:58:00',
    metricLabel: '조회수',
    metricValue: 271,
    sales: 3,
    revenue: '298만',
    productCount: 29,
  },
  {
    rank: 5,
    title: '[슈퍼워크]여름 전싱품 9900원부터~사은품증정50명',
    channel: '그립',
    category: '패션의류',
    broadcastTime: '2026-07-17T15:00:00',
    metricLabel: '조회수',
    metricValue: 2710,
    sales: 159,
    revenue: '239만',
    productCount: 3,
  },
  {
    rank: 6,
    title: '[7/17] JBL X 하만카돈 스피커 이어폰 썸머 이벤트',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T15:00:00',
    metricLabel: '조회수',
    metricValue: 350,
    sales: 10,
    revenue: '202만',
    productCount: 30,
  },
  {
    rank: 7,
    title: '[AI]⭐삼성 청소기, 에어컨⭐ 삼성이 선물하는 스마트 라이프',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T16:00:00',
    metricLabel: '조회수',
    metricValue: 140,
    sales: 2,
    revenue: '175만',
    productCount: 52,
  },
  {
    rank: 8,
    title: '라미러브의❤️주말 세일 특가❤️',
    channel: '네이버쇼핑LIVE',
    category: '패션의류',
    broadcastTime: '2026-07-17T15:32:00',
    metricLabel: '조회수',
    metricValue: 606,
    sales: 89,
    revenue: '155만',
    productCount: 99,
  },
  {
    rank: 9,
    title: 'JBL 사운드바 무선헤드폰 블루투스스피커 어린이헤드셋 특가',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T14:58:00',
    metricLabel: '조회수',
    metricValue: 316,
    sales: 6,
    revenue: '102만',
    productCount: 42,
  },
  {
    rank: 10,
    title: '[AI라이브] 무더운여름 캐리어 가전 에어컨 & 제습기 라이브 혜택',
    channel: '네이버쇼핑LIVE',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T16:00:00',
    metricLabel: '조회수',
    metricValue: 48,
    sales: 3,
    revenue: '97.7만',
    productCount: 19,
  },
]

// 2026-07-17 (금) 기준, 로그인 상태에서 직접 확인한 스냅샷.
// 시청률은 원본 API 응답 자체에 대응 필드가 없어(백엔드가 값을 안 내려줌) 전 행 null 처리.
export const homeShoppingBroadcasts = [
  {
    rank: 1,
    title: '삼성에어컨',
    channel: 'NS홈쇼핑',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T15:20:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 110,
    revenue: '2.12억',
    productCount: 4,
  },
  {
    rank: 2,
    title: '제습기 뽀송 24L DXWH248-PEK',
    channel: 'CJ온스타일',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T15:30:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 226,
    revenue: '1.42억',
    productCount: 1,
  },
  {
    rank: 3,
    title: '[신애라PICK]/최신최고급]마이어 방수 텀블렌더(전용 스텐보냉텀블러 포함)',
    channel: '현대홈쇼핑',
    category: '디지털/가전',
    broadcastTime: '2026-07-17T15:30:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 1967,
    revenue: '1.37억',
    productCount: 1,
  },
  {
    rank: 4,
    title:
      '[르제 씨아클라] ★역대최다구성/한창서패키지★ 씨아클라 클렌저 120ml * 4 + 해면 * 2 + (리뷰시) 클렌저 본품 120ml 1병 더',
    channel: '롯데홈쇼핑',
    category: '화장품/미용',
    broadcastTime: '2026-07-17T15:30:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 564,
    revenue: '1.23억',
    productCount: 4,
  },
  {
    rank: 5,
    title: '스튜디오디페 26SS 셔링 경량 블라우스 3종[런칭 가격 79,900원]',
    channel: 'GS홈쇼핑 마이샵',
    category: '패션의류',
    broadcastTime: '2026-07-17T15:38:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 1736,
    revenue: '1.19억',
    productCount: 2,
  },
  {
    rank: 6,
    title: '[특집] 사임당 찰떡 6종세트(90+10개)',
    channel: '공영쇼핑',
    category: '식품',
    broadcastTime: '2026-07-17T15:40:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 1967,
    revenue: '9812만',
    productCount: 23,
  },
  {
    rank: 7,
    title: '하이뮨 프로틴밸런스 알파 12캔+블루베리 1박스',
    channel: 'GS홈쇼핑',
    category: '식품',
    broadcastTime: '2026-07-17T15:30:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 293,
    revenue: '8081만',
    productCount: 2,
  },
  {
    rank: 8,
    title: '(SK 단독세일) 신영와코루 로맨틱블룸 인견 쿨링 젤리 브라팬티(10종)',
    channel: 'SK스토아',
    category: '패션의류',
    broadcastTime: '2026-07-17T15:31:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 714,
    revenue: '7847만',
    productCount: 1,
  },
  {
    rank: 9,
    title: '제주 보우짱 미니 밤호박 9kg(과당 300~500g / 18~30개)',
    channel: '신세계쇼핑',
    category: '식품',
    broadcastTime: '2026-07-17T15:34:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 2219,
    revenue: '6055만',
    productCount: 4,
  },
  {
    rank: 10,
    title: '[맥스튜어트뉴욕] 여성 씬 에어라이트 데님 3종',
    channel: '홈앤쇼핑',
    category: '패션의류',
    broadcastTime: '2026-07-17T16:00:00',
    metricLabel: '시청률',
    metricValue: null,
    sales: 724,
    revenue: '4561만',
    productCount: 1,
  },
]
